repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run CTest before commit
        entry: ./pre-commit/run-tests-multiplatform.py
        language: system
        files: ^(.*)$ # All files
        stages: [commit]