repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run CTest before commit
        entry: /usr/bin/env bash ./pre-commit/run-tests.sh
        language: script
        stages: [commit]
